### ISSUE TITLE
Add custom indexKeys on top of default one

### ISSUE THREAD

**Issue by foufrix** [lukeocodes/netlify-plugin-algolia-export#6]
**Is your feature request related to a problem? Please describe.**
Impossible to export custom attribute into algolia, only default one defined in the code are possible : 
```javascript
const indexKeys = [
  'title',
  'description',
  'text',
  'image',
  'headings',
  'keywords',
  'from'
]
```

**Describe the solution you'd like**
Be able to add in plugin config in `netlify.toml`file custom index keys.

What do you think about it ?

**Comment by foufrix** [comment]
also i tried with the key `keywords` as i saw it in the source code, it's not imported neither, is this a bug ? :
```yml
---
title: How to center elements or <div> with CSS.
date: "2020-04-06"
description: Quickly center child component in parents using CSS attributes.
keywords: ["css"]
---
```

And here what i have in algolia after successful import from netlify build console :
![image](https://user-images.githubusercontent.com/16646581/88177610-795bb480-cc29-11ea-9215-b27c05b82f70.png)
